services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile.prod
      network: host  # Temporary network access for Supabase CLI during build only
    networks:
      - app-network
    ports:
      - "3001:3001"
    env_file:
      - packages/backend/.env-prod
    environment:
      - NODE_ENV=production
      - DOCKER=true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile.prod
    ports:
      - "8080:80"
    env_file:
      - packages/frontend/.env-prod
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: 2001:db8::/32
